//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_DM_TU_DIEN
    {
        public CM_DM_TU_DIEN()
        {
            this.DM_KHACH_HANG = new HashSet<DM_KHACH_HANG>();
            this.GD_NGUOI_QUAN_LY_KHACH_HANG = new HashSet<GD_NGUOI_QUAN_LY_KHACH_HANG>();
            this.DM_ACTION = new HashSet<DM_ACTION>();
        }
    
        public System.Guid ID { get; set; }
        public string TEN_TU_DIEN { get; set; }
        public string MA_TU_DIEN { get; set; }
        public System.Guid ID_LOAI_TU_DIEN { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual CM_DM_LOAI_TD CM_DM_LOAI_TD { get; set; }
        public virtual ICollection<DM_KHACH_HANG> DM_KHACH_HANG { get; set; }
        public virtual ICollection<GD_NGUOI_QUAN_LY_KHACH_HANG> GD_NGUOI_QUAN_LY_KHACH_HANG { get; set; }
        public virtual ICollection<DM_ACTION> DM_ACTION { get; set; }
    }
}
