//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BKI_CRMEntities : DbContext
    {
        public BKI_CRMEntities()
            : base("name=BKI_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CM_DM_LOAI_TD> CM_DM_LOAI_TD { get; set; }
        public DbSet<CM_DM_TU_DIEN> CM_DM_TU_DIEN { get; set; }
        public DbSet<DM_CHUYEN_TRANG_THAI> DM_CHUYEN_TRANG_THAI { get; set; }
        public DbSet<DM_CONG_TY> DM_CONG_TY { get; set; }
        public DbSet<DM_KHACH_HANG> DM_KHACH_HANG { get; set; }
        public DbSet<DM_NHOM_SAN_PHAM> DM_NHOM_SAN_PHAM { get; set; }
        public DbSet<DM_PHONG_BAN> DM_PHONG_BAN { get; set; }
        public DbSet<DM_SAN_PHAM> DM_SAN_PHAM { get; set; }
        public DbSet<DM_TRANG_THAI> DM_TRANG_THAI { get; set; }
        public DbSet<DM_YEU_CAU_TRANG_THAI> DM_YEU_CAU_TRANG_THAI { get; set; }
        public DbSet<GD_CHUYEN_TRANG_THAI> GD_CHUYEN_TRANG_THAI { get; set; }
        public DbSet<GD_KHACH_HANG_SU_DUNG_SAN_PHAM> GD_KHACH_HANG_SU_DUNG_SAN_PHAM { get; set; }
        public DbSet<GD_NGUOI_QUAN_LY_KHACH_HANG> GD_NGUOI_QUAN_LY_KHACH_HANG { get; set; }
        public DbSet<HT_PHAN_QUYEN_CHO_NHOM> HT_PHAN_QUYEN_CHO_NHOM { get; set; }
        public DbSet<HT_PHAN_QUYEN_HE_THONG> HT_PHAN_QUYEN_HE_THONG { get; set; }
        public DbSet<HT_USER> HT_USER { get; set; }
        public DbSet<HT_USER_GROUP> HT_USER_GROUP { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<V_DM_NHAN_VIEN_CONG_TY> V_DM_NHAN_VIEN_CONG_TY { get; set; }
        public DbSet<V_DM_YEU_CAU_TRANG_THAI> V_DM_YEU_CAU_TRANG_THAI { get; set; }
        public DbSet<V_GD_CHUYEN_TRANG_THAI> V_GD_CHUYEN_TRANG_THAI { get; set; }
        public DbSet<V_GD_KHACH_HANG_CHUYEN_TRANG_THAI> V_GD_KHACH_HANG_CHUYEN_TRANG_THAI { get; set; }
        public DbSet<V_GD_LICH_SU_KHACH_HANG> V_GD_LICH_SU_KHACH_HANG { get; set; }
        public DbSet<V_GD_NGUOI_QUAN_LY_KHACH_HANG> V_GD_NGUOI_QUAN_LY_KHACH_HANG { get; set; }
        public DbSet<V_RPT_LUY_KE> V_RPT_LUY_KE { get; set; }
        public DbSet<V_RPT_PHAT_SINH_TRONG_THANG> V_RPT_PHAT_SINH_TRONG_THANG { get; set; }
    }
}
