//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUYEN_TRANG_THAI
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_TRANG_THAI_BAN_DAU { get; set; }
        public System.Guid ID_TRANG_THAI_SAU { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DM_TRANG_THAI DM_TRANG_THAI { get; set; }
        public virtual DM_TRANG_THAI DM_TRANG_THAI1 { get; set; }
    }
}
