//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHONG_BAN
    {
        public DM_PHONG_BAN()
        {
            this.HT_USER = new HashSet<HT_USER>();
        }
    
        public System.Guid ID { get; set; }
        public string TEN_PHONG_BAN { get; set; }
        public string MA_PHONG_BAN { get; set; }
        public System.Guid ID_CONG_TY { get; set; }
    
        public virtual DM_CONG_TY DM_CONG_TY { get; set; }
        public virtual ICollection<HT_USER> HT_USER { get; set; }
    }
}
