//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TRANG_THAI
    {
        public DM_TRANG_THAI()
        {
            this.DM_CHUYEN_TRANG_THAI = new HashSet<DM_CHUYEN_TRANG_THAI>();
            this.DM_CHUYEN_TRANG_THAI1 = new HashSet<DM_CHUYEN_TRANG_THAI>();
            this.DM_YEU_CAU_TRANG_THAI = new HashSet<DM_YEU_CAU_TRANG_THAI>();
            this.GD_CHUYEN_TRANG_THAI = new HashSet<GD_CHUYEN_TRANG_THAI>();
        }
    
        public System.Guid ID { get; set; }
        public string MA_TRANG_THAI { get; set; }
        public string MO_TA { get; set; }
        public bool LOAI_TRANG_THAI_YN { get; set; }
        public System.Guid ID_CONG_TY { get; set; }
    
        public virtual ICollection<DM_CHUYEN_TRANG_THAI> DM_CHUYEN_TRANG_THAI { get; set; }
        public virtual ICollection<DM_CHUYEN_TRANG_THAI> DM_CHUYEN_TRANG_THAI1 { get; set; }
        public virtual DM_CONG_TY DM_CONG_TY { get; set; }
        public virtual ICollection<DM_YEU_CAU_TRANG_THAI> DM_YEU_CAU_TRANG_THAI { get; set; }
        public virtual ICollection<GD_CHUYEN_TRANG_THAI> GD_CHUYEN_TRANG_THAI { get; set; }
    }
}
