//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_YEU_CAU_TRANG_THAI
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_TRANG_THAI { get; set; }
        public string YEU_CAU { get; set; }
        public Nullable<int> THU_TU { get; set; }
    
        public virtual DM_TRANG_THAI DM_TRANG_THAI { get; set; }
    }
}
