//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_ACTION
    {
        public System.Guid ID { get; set; }
        public System.DateTime TAI_NGAY { get; set; }
        public System.Guid ID_USER { get; set; }
        public string LAM_GI { get; set; }
        public string GHI_CHU_1 { get; set; }
        public string GHI_CHU_2 { get; set; }
    
        public virtual HT_USER HT_USER { get; set; }
    }
}
