//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_PHIEN_LAM_VIEC
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ID_NHAN_VIEN { get; set; }
        public Nullable<System.Guid> ID_KHACH_HANG { get; set; }
        public string NOI_DUNG_PHIEN_LAM_VIEC { get; set; }
    }
}
