//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_PHAN_QUYEN_HE_THONG
    {
        public HT_PHAN_QUYEN_HE_THONG()
        {
            this.HT_PHAN_QUYEN_CHO_NHOM = new HashSet<HT_PHAN_QUYEN_CHO_NHOM>();
        }
    
        public System.Guid ID { get; set; }
        public string TEN_QUYEN { get; set; }
        public string MA_QUYEN { get; set; }
    
        public virtual ICollection<HT_PHAN_QUYEN_CHO_NHOM> HT_PHAN_QUYEN_CHO_NHOM { get; set; }
    }
}
