//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GD_KHACH_HANG_CHUYEN_TRANG_THAI
    {
        public System.Guid ID { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string MA_TRANG_THAI { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public string SAN_PHAM_SU_DUNG { get; set; }
        public Nullable<decimal> SO_TIEN_DA_NHAN { get; set; }
        public string GHI_CHU { get; set; }
        public System.Guid ID_TRANG_THAI { get; set; }
    }
}
