//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HT_PHAN_QUYEN_CHI_TIET
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_ACTION { get; set; }
        public System.Guid ID_USER_GROUP { get; set; }
        public string ACTION_NAME { get; set; }
        public string TEN_NHOM_NGUOI_SU_DUNG { get; set; }
        public System.Guid ID_CONTROLLER { get; set; }
        public string CONTROLLER_NAME { get; set; }
    }
}
