//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NHAN_VIEN_QUAN_LY_KHACH_HANG
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_USER_GROUP { get; set; }
        public string TEN_NHOM_NGUOI_SU_DUNG { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public bool ACTIVE_YN_USER { get; set; }
        public Nullable<System.Guid> ID_USER_CAP_TREN { get; set; }
        public string HO_TEN_NHAN_VIEN { get; set; }
        public Nullable<System.Guid> ID_PHONG_BAN { get; set; }
        public string SDT01 { get; set; }
        public string SDT02 { get; set; }
        public string EMAIL { get; set; }
        public string ANH_CA_NHAN { get; set; }
        public Nullable<System.Guid> ID_GD_NGUOI_QUAN_LY_KHACH_HANG { get; set; }
        public Nullable<System.Guid> ID_QUYEN_QUAN_LY { get; set; }
        public string TEN_QUYEN_QUAN_LY { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_QUYEN { get; set; }
        public Nullable<bool> ACTIVE_YN_NGUOI_QL_KH { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<System.Guid> ID_KHACH_HANG_SU_DUNG_SAN_PHAM { get; set; }
        public Nullable<System.Guid> ID_KHACH_HANG { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public Nullable<System.Guid> ID_LOAI_KHACH_HANG { get; set; }
        public string TEN_LOAI_KHACH_HANG { get; set; }
        public Nullable<System.Guid> ID_SAN_PHAM { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public Nullable<decimal> GIA_SAN_PHAM { get; set; }
        public Nullable<System.Guid> ID_NHOM_SAN_PHAM { get; set; }
        public string TEN_NHOM_SAN_PHAM { get; set; }
    }
}
