//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TU_DIEN
    {
        public System.Guid ID_LOAI { get; set; }
        public string TEN_LOAI_TU_DIEN { get; set; }
        public System.Guid ID { get; set; }
        public string TEN_TU_DIEN { get; set; }
        public string GHI_CHU { get; set; }
    }
}
