//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHACH_HANG
    {
        public DM_KHACH_HANG()
        {
            this.GD_CHUYEN_TRANG_THAI = new HashSet<GD_CHUYEN_TRANG_THAI>();
            this.GD_NGUOI_QUAN_LY_KHACH_HANG = new HashSet<GD_NGUOI_QUAN_LY_KHACH_HANG>();
        }
    
        public System.Guid ID { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public System.Guid ID_LOAI_KHACH_HANG { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string DIA_CHI { get; set; }
        public string NGUOI_GIOI_THIEU { get; set; }
        public Nullable<bool> GIOI_TINH { get; set; }
        public string THONG_TIN_BO_SUNG_01 { get; set; }
        public string THONG_TIN_BO_SUNG_02 { get; set; }
        public string THONG_TIN_BO_SUNG_03 { get; set; }
        public string THONG_TIN_BO_SUNG_04 { get; set; }
        public string THONG_TIN_BO_SUNG_05 { get; set; }
        public string SAN_PHAM_SU_DUNG { get; set; }
        public Nullable<System.Guid> ID_SAN_PHAM_SU_DUNG { get; set; }
    
        public virtual CM_DM_TU_DIEN CM_DM_TU_DIEN { get; set; }
        public virtual DM_SAN_PHAM DM_SAN_PHAM { get; set; }
        public virtual ICollection<GD_CHUYEN_TRANG_THAI> GD_CHUYEN_TRANG_THAI { get; set; }
        public virtual ICollection<GD_NGUOI_QUAN_LY_KHACH_HANG> GD_NGUOI_QUAN_LY_KHACH_HANG { get; set; }
    }
}
