//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHOM_SAN_PHAM
    {
        public DM_NHOM_SAN_PHAM()
        {
            this.DM_SAN_PHAM = new HashSet<DM_SAN_PHAM>();
        }
    
        public System.Guid ID { get; set; }
        public string TEN_NHOM_SAN_PHAM { get; set; }
        public string MA_NHOM_SAN_PHAM { get; set; }
        public System.Guid ID_CONG_TY { get; set; }
    
        public virtual DM_CONG_TY DM_CONG_TY { get; set; }
        public virtual ICollection<DM_SAN_PHAM> DM_SAN_PHAM { get; set; }
    }
}
