//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_SAN_PHAM
    {
        public DM_SAN_PHAM()
        {
            this.DM_KHACH_HANG = new HashSet<DM_KHACH_HANG>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ID_NHOM_SAN_PHAM { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public Nullable<decimal> GIA_SAN_PHAM { get; set; }
        public string THONG_TIN_BO_SUNG_01 { get; set; }
        public string THONG_TIN_BO_SUNG_02 { get; set; }
        public string THONG_TIN_BO_SUNG_03 { get; set; }
        public string THONG_TIN_BO_SUNG_04 { get; set; }
        public string THONG_TIN_BO_SUNG_05 { get; set; }
    
        public virtual ICollection<DM_KHACH_HANG> DM_KHACH_HANG { get; set; }
        public virtual DM_NHOM_SAN_PHAM DM_NHOM_SAN_PHAM { get; set; }
    }
}
