//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_LOG
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_NHAN_VIEN { get; set; }
        public string COT_DA_SUA { get; set; }
        public string GIA_TRI_CU { get; set; }
        public string GIA_TRI_MOI { get; set; }
    }
}
