//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_PHAN_QUYEN_CHO_NHOM
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_PHAN_QUYEN_HE_THONG { get; set; }
        public System.Guid ID_NHOM_NGUOI_SU_DUNG { get; set; }
    
        public virtual HT_PHAN_QUYEN_HE_THONG HT_PHAN_QUYEN_HE_THONG { get; set; }
        public virtual HT_USER_GROUP HT_USER_GROUP { get; set; }
    }
}
