//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DM_KHACH_HANG
    {
        public string TEN_SAN_PHAM { get; set; }
        public System.Guid ID { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string MA_SO_THUE { get; set; }
        public Nullable<System.Guid> ID_LOAI_KHACH_HANG { get; set; }
        public string SDT { get; set; }
        public string SDT_02 { get; set; }
        public string EMAIL { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<System.DateTime> HAN_KHACH_HANG { get; set; }
        public Nullable<bool> GIOI_TINH { get; set; }
        public string THONG_TIN_BO_SUNG_01 { get; set; }
        public string THONG_TIN_BO_SUNG_02 { get; set; }
        public string THONG_TIN_BO_SUNG_03 { get; set; }
        public string THONG_TIN_BO_SUNG_04 { get; set; }
        public string THONG_TIN_BO_SUNG_05 { get; set; }
        public Nullable<System.Guid> ID_CONG_TY { get; set; }
        public string IMAGE { get; set; }
        public string NOI_CONG_TAC { get; set; }
        public string FACEBOOK { get; set; }
        public string SKYPE { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public System.Guid ID_GD { get; set; }
    }
}
