//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DM_NHAN_VIEN_CONG_TY
    {
        public System.Guid ID { get; set; }
        public string HO_TEN_NHAN_VIEN { get; set; }
        public System.Guid ID_NHAN_VIEN { get; set; }
        public string TEN_CONG_TY { get; set; }
    }
}
