//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GD_CHUYEN_TRANG_THAI
    {
        public string TRANG_THAI_DAU { get; set; }
        public string MA_TRANG_THAI { get; set; }
        public System.Guid ID_TRANG_THAI_SAU { get; set; }
        public bool LOAI_TRANG_THAI_YN { get; set; }
        public System.Guid ID_TRANG_THAI_BAN_DAU { get; set; }
    }
}
