//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HT_USER
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_USER_GROUP { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public bool ACTIVE_YN { get; set; }
        public Nullable<System.Guid> ID_USER_CAP_TREN { get; set; }
        public string TEN_SEP { get; set; }
        public string TEN_NHAN_VIEN { get; set; }
        public Nullable<System.Guid> ID_PHONG_BAN { get; set; }
        public string TEN_PHONG_BAN { get; set; }
        public string MA_PHONG_BAN { get; set; }
        public string SDT01 { get; set; }
        public string SDT02 { get; set; }
        public string EMAIL { get; set; }
        public string ANH_CA_NHAN { get; set; }
        public string TEN_NHOM_NGUOI_SU_DUNG { get; set; }
        public string TEN_CONG_TY { get; set; }
        public System.Guid ID_CONG_TY { get; set; }
    }
}
