//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RPT_PHAT_SINH_TRONG_THANG
    {
        public string MA_TRANG_THAI { get; set; }
        public Nullable<int> LUY_KE { get; set; }
    }
}
